vim.g.mapleader = " "
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostics list' })
vim.keymap.set('n', '<leader>cx', vim.cmd.NvimTreeToggle)

vim.keymap.set('n', '<leader>c', "*#cgn")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "*", "*zz")
vim.keymap.set("n", "#", "#zz")
vim.keymap.set("n", "N", "Nzz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("i", "<C-f>", "<Right>")
vim.keymap.set("i", "<C-b>", "<Left>")
vim.keymap.set("x", "p", "\"_dP")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>s", ":%s/\\<<C-r><C-w>\\>/" )
vim.keymap.set("v", "<leader>s", "\"ay:%s/\\<<C-r>a\\>/" )
vim.keymap.set("n", "<leader>/", "/\\<\\><Left><Left>")
vim.keymap.set("n", "<leader>?", "?\\<\\><Left><Left>")
vim.keymap.set("n", "<leader>h", "<C-^>")
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "<C-w>o", "<C-w>o:lua MiniMap.open()<CR>")
vim.keymap.set("n", "<leader>df", vim.diagnostic.open_float, { desc = 'Open diagnostics float' })
vim.keymap.set("o", "<C-c>", "<C-g>")
vim.keymap.set("n", "0", "^")
vim.keymap.set("n", "^", "0")
vim.keymap.set("t", "<C-q>", "<C-\\><C-n>")
